
/**
 * This page was generated by Claude
 */

import React, { useState } from 'react';
import { Music, Users, AlertCircle, QrCode } from 'lucide-react';
import Authentication from '../utils/auth.js';
import Camera from '../utils/Camera.js';

export default function SpotifyLoginWireframe() {
    const [currentScreen, setCurrentScreen] = useState('login');
    const [login, setLoggedIn] = useState(false); //


    const LoginScreen = () => (
        <div className="max-w-md mx-auto bg-white dark:bg-gray-900 min-h-screen flex flex-col">
            {/* Header */}
            <div className="bg-green-500 dark:bg-green-600 text-white p-6 text-center">
                <Music className="mx-auto mb-2" size={48} />
                <h1 className="text-2xl font-bold">Pizza Party</h1>
                <p className="text-green-100 dark:text-green-200 text-sm">Powered by Spotify</p>
            </div>

            {/* Main Content */}
            <div className="flex-1 p-6 space-y-6">
                {/* Premium Notice */}
                <div className="bg-yellow-50 dark:bg-yellow-900/30 border border-yellow-200 dark:border-yellow-700 rounded-lg p-4">
                    <div className="flex items-start space-x-3">
                        <AlertCircle className="text-yellow-600 dark:text-yellow-400 mt-0.5 flex-shrink-0" size={20} />
                        <div>
                            <h3 className="font-semibold text-yellow-800 dark:text-yellow-300 text-sm">Premium Required</h3>
                            <p className="text-yellow-700 dark:text-yellow-400 text-sm mt-1">
                                A Spotify Premium account is required to access all features including queue control and playback.
                            </p>
                        </div>
                    </div>
                </div>

                {/* Login Button */}
                <button
                    className="w-full bg-green-500 hover:bg-green-600 dark:bg-green-600 dark:hover:bg-green-700 text-white font-semibold py-4 px-6 rounded-lg flex items-center justify-center space-x-2 transition-colors"
                    onClick={() => setLoggedIn(true)}
                >
                    <Music size={20} />
                    <span>Connect with Spotify</span>
                </button>
                {login ? <Authentication /> : null}
                {/* Divider */}
                <div className="flex items-center space-x-4">
                    <div className="flex-1 h-px bg-gray-300 dark:bg-gray-600"></div>
                    <span className="text-gray-500 dark:text-gray-400 text-sm">or</span>
                    <div className="flex-1 h-px bg-gray-300 dark:bg-gray-600"></div>
                </div>

                {/* Join Party Option */}
                <div className="text-center space-y-4">
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200">Don't have Spotify Premium?</h3>
                    <p className="text-gray-600 dark:text-gray-400 text-sm">
                        You can still join someone else's music party by scanning their QR code
                    </p>

                    <button
                        onClick={() => setCurrentScreen('qr-scanner')}
                        className="w-full bg-gray-100 hover:bg-gray-200 dark:bg-gray-800 dark:hover:bg-gray-700 text-gray-800 dark:text-gray-200 font-medium py-3 px-6 rounded-lg flex items-center justify-center space-x-2 transition-colors border border-gray-300 dark:border-gray-600"
                    >
                        <QrCode size={20} />
                        <span>Scan QR Code to Join Party</span>
                    </button>
                </div>
            </div>

            {/* Footer */}
            <div className="p-4 text-center text-xs text-gray-500 dark:text-gray-400">
                By connecting, you agree to our Terms of Service
            </div>
        </div>
    );

    const QRScannerScreen = () => (
        <div className="max-w-md mx-auto bg-white dark:bg-gray-900 min-h-screen flex flex-col">
            {/* Header */}
            <div className="bg-green-500 dark:bg-green-600 text-white p-4 flex items-center">
                <button
                    onClick={() => setCurrentScreen('login')}
                    className="text-white hover:text-green-200 dark:hover:text-green-300 mr-4"
                >
                    ←
                </button>
                <h1 className="text-lg font-semibold">Join Music Party</h1>
            </div>

            {/* Main Content */}
            <div className="flex-1 p-6 space-y-6">
                {/* QR Scanner Placeholder */}

                <div className="bg-gray-100 dark:bg-gray-800 border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-lg p-8 text-center">
                    <Camera />
                </div>

                {/* Instructions */}
                <div className="space-y-4">
                    <h3 className="font-semibold text-gray-800 dark:text-gray-200">How to join:</h3>
                    <div className="space-y-3">
                        <div className="flex items-start space-x-3">
                            <div className="bg-green-500 dark:bg-green-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-semibold">1</div>
                            <p className="text-gray-700 dark:text-gray-300 text-sm">Ask the party host to show their QR code</p>
                        </div>
                        <div className="flex items-start space-x-3">
                            <div className="bg-green-500 dark:bg-green-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-semibold">2</div>
                            <p className="text-gray-700 dark:text-gray-300 text-sm">Point your camera at the QR code</p>
                        </div>
                        <div className="flex items-start space-x-3">
                            <div className="bg-green-500 dark:bg-green-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm font-semibold">3</div>
                            <p className="text-gray-700 dark:text-gray-300 text-sm">Start adding songs to the queue!</p>
                        </div>
                    </div>
                </div>

                {/* Note */}
                <div className="bg-blue-50 dark:bg-blue-900/30 border border-blue-200 dark:border-blue-700 rounded-lg p-4">
                    <div className="flex items-start space-x-3">
                        <Users className="text-blue-600 dark:text-blue-400 mt-0.5 flex-shrink-0" size={20} />
                        <div>
                            <h4 className="font-semibold text-blue-800 dark:text-blue-300 text-sm">Guest Mode</h4>
                            <p className="text-blue-700 dark:text-blue-400 text-sm mt-1">
                                As a guest, you can search and add songs to the queue, but playback control stays with the host.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );

    return (
        <div className="bg-gray-50 dark:bg-gray-900 min-h-screen p-4 transition-colors">
            {/* Current Screen */}
            <div className="shadow-lg dark:shadow-gray-900/50 rounded-lg overflow-hidden">
                {currentScreen === 'login' && <LoginScreen />}
                {currentScreen === 'qr-scanner' && <QRScannerScreen />}
            </div>
        </div>
    );
}